name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - run: npm i

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      run-test: ${{ steps.detect.outputs.run-test }}
    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changes
        run: |
          echo "Checking for changes..."
          CHANGED_FILES=$(git diff --name-only @{u} ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Determine if tests should run
        id: detect
        run: |
          TEST_PATHS="^(example-application/|librairies/|src/|tests/|test/|package.json|tsconfig.json|jest.config.js|recipes/nestjs/)"
          if echo "${{ steps.changes.outputs.files }}" | grep -qE "$TEST_PATHS"; then
            echo "::set-output name=run-test::true"
          else
            echo "::set-output name=run-test::false"
          fi

  test:
    needs: [build, detect-changes]
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.run-test == 'true'
    strategy:
      matrix:
        test-suite: [ "test", "test:nestjs", "test:mocha" ]

    steps:
      - uses: actions/checkout@v2
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version: "${{ needs.build.outputs.NVMRC }}"

      - name: Cache Node.js modules (for tests)
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Run ${{ matrix.test-suite }}
        run: npm run ${{ matrix.test-suite }}
